version: "3"
services:
  php:
    build: ./docker/php/
    volumes:
      - ./webroot/:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d/
  webserver:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webroot/:/var/www/html
