version: "3"
services:
  php:
    build: ./docker/php/
    volumes:
      - ./bedrock/:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d/
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 81:81
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./bedrock/:/var/www/html
    links:
      - php
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - 8001:80
    environment:
      MYSQL_ROOT_PASSOWRD: root
      UPLOAD_LIMIT: 300M
volumes:
  db_data: {}
