version: "3"
services:
  php:

    build: ./docker/php/
    volumes:
      - ./webroot/:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d/
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 81:81
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webroot/:/var/www/html
    links:
      - php
      - mysql
  mysql:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'root'
        MYSQL_DATABASE: 'root'
    ports:
        - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    ports:
        - 8081:8080
    links:
      - php
      - mysql
volumes:
  db_data: {}